Update checkBuild.yml

diff --git a/.github/workflows/checkBuild.yml b/.github/workflows/checkBuild.yml
--- a/.github/workflows/checkBuild.yml
+++ b/.github/workflows/checkBuild.yml
@@ -12,54 +12,12 @@ on:
       - '**.md'
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    
-    steps:
-    - uses: actions/checkout@v2
-      
-    - name: Set up JDK 8
-      uses: actions/setup-java@v2
-      with:
-        distribution: 'zulu'
-        java-version: '8'
-        java-package: jdk+fx
-
-    - name: Cache local Maven repository
-      uses: actions/cache@v2
-      with:
-        path: ~/.m2/repository
-        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-maven-
-      
-    - name: Build with Maven
-      run: mvn -B clean verify
-      
-    - name: Check for uncommited changes
-      run: |
-        if [[ "$(git status --porcelain)" != "" ]]; then
-          echo ----------------------------------------
-          echo git status
-          echo ----------------------------------------
-          git status
-          echo ----------------------------------------
-          echo git diff
-          echo ----------------------------------------
-          git diff
-          echo ----------------------------------------
-          echo Troubleshooting
-          echo ----------------------------------------
-          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean verify"
-          exit 1
-        fi
-
   build_lts:
     runs-on: ubuntu-latest
     
     strategy:
       matrix:
-        java: [8, 11, 17]
+        java: [8, 11] #, 17]
 
     steps:
     - uses: actions/checkout@v2
@@ -85,6 +43,25 @@ jobs:
     - name: Debug
       run: ls -lha target
       
+    - name: Check for uncommited changes
+      run: |
+        if [[ "$(git status --porcelain)" != "" ]]; then
+          echo ----------------------------------------
+          echo git status
+          echo ----------------------------------------
+          git status
+          echo ----------------------------------------
+          echo git diff
+          echo ----------------------------------------
+          git diff
+          echo ----------------------------------------
+          echo Troubleshooting
+          echo ----------------------------------------
+          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean verify"
+          exit 1
+        fi
+
+      
   build_xdev_ide:
     runs-on: ubuntu-latest
     
@@ -107,7 +84,7 @@ jobs:
           ${{ runner.os }}-maven-
       
     - name: Build with Maven
-      run: mvn -B clean verify -Pxdev-ide
+      run: mvn -B clean verify -Pjava8,xdev-ide
       
     - name: Debug
       run: ls -lha target
